import "package:flutter/material.dart";

class AppText {
  static final Map<String, Map<String, String>> data = {
    "en": {
      "app": "daftr",
      "login": "Login",
      "register": "Register",
      "email": "Email",
      "password": "Password",
      "name": "Name",
      "logout": "Logout",
      "inventory": "Inventory",
      "damagedGoods": "Damaged Goods",
      "sales": "Sales",
      "reports": "Reports",
      "settings": "Settings",
      "invoiceTemplate": "Invoice Template",
      "records": "Records",
      "expenses": "Expenses",
      "debts": "Debts",
      "contacts": "Names",
      "about": "About",
      "addProduct": "Add Product",
      "addVariant": "Add Variant",
      "productName": "Product Name",
      "sku": "SKU",
      "imageUrl": "Image URL",
      "purchasePrice": "Purchase Price",
      "sellingPrice": "Selling Price",
      "quantity": "Quantity",
      "minStock": "Minimum Stock",
      "currency": "Currency",
      "unit": "Unit",
      "piece": "Piece",
      "bag": "Bag",
      "kilogram": "Kilogram",
      "box": "Box",
      "save": "Save",
      "cancel": "Cancel",
      "delete": "Delete",
      "adjustStock": "Adjust Stock",
      "newQuantity": "New Quantity",
      "reason": "Reason",
      "products": "Products",
      "totalQty": "Total Qty",
      "lowStock": "Low Stock",
      "allProducts": "All Products",
      "stock": "Stock",
      "inStock": "In Stock",
      "productDetails": "Product Details",
      "variants": "Variants",
      "newSale": "New Sale",
      "customerName": "Customer Name",
      "selectProduct": "Select Product",
      "unitPrice": "Unit Price",
      "createSale": "Create Sale",
      "recentSales": "Recent Sales",
      "invoiceNo": "Invoice No.",
      "printInvoice": "Print Invoice",
      "businessName": "Business Name",
      "businessPhone": "Business Phone",
      "businessAddress": "Business Address",
      "invoiceTitle": "Invoice Title",
      "footerNote": "Footer Note",
      "terms": "Terms",
      "logoUrl": "Logo URL",
      "color": "Color",
      "showLogo": "Show Logo",
      "showSignature": "Show Signature",
      "preview": "Preview",
      "signature": "Signature",
      "billTo": "Bill To",
      "stockMovements": "Stock Movements",
      "language": "Language",
      "theme": "Theme",
      "english": "English",
      "arabic": "Arabic",
      "light": "Light",
      "dark": "Dark",
      "system": "System",
      "exchangeRate": "Exchange Rate",
      "salesTotal": "Sales Total",
      "profit": "Profit",
      "comingSoon": "Coming soon",
      "empty": "No data yet.",
      "error": "Error",
      "refresh": "Refresh"
    },
    "ar": {
      "app": "daftr",
      "login": "تسجيل الدخول",
      "register": "إنشاء حساب",
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "name": "الاسم",
      "logout": "تسجيل الخروج",
      "inventory": "المخزون",
      "damagedGoods": "البضاعة التالفة",
      "sales": "المبيع",
      "reports": "التقارير",
      "settings": "الإعدادات",
      "invoiceTemplate": "نموذج الفاتورة",
      "records": "السجلات",
      "expenses": "المصاريف",
      "debts": "الديون",
      "contacts": "الأسماء",
      "about": "حول التطبيق",
      "addProduct": "إضافة منتج",
      "addVariant": "إضافة صنف",
      "productName": "اسم المنتج",
      "sku": "الكود",
      "imageUrl": "رابط الصورة",
      "purchasePrice": "سعر الشراء",
      "sellingPrice": "سعر المبيع",
      "quantity": "الكمية",
      "minStock": "حد المخزون",
      "currency": "العملة",
      "unit": "الوحدة",
      "piece": "حبة",
      "bag": "كيس",
      "kilogram": "كيلو",
      "box": "علبة",
      "save": "حفظ",
      "cancel": "إلغاء",
      "delete": "حذف",
      "adjustStock": "تعديل المخزون",
      "newQuantity": "الكمية الجديدة",
      "reason": "السبب",
      "products": "المنتجات",
      "totalQty": "إجمالي الكمية",
      "lowStock": "مخزون منخفض",
      "allProducts": "جميع المنتجات",
      "stock": "المخزون",
      "inStock": "متوفر",
      "productDetails": "تفاصيل المنتج",
      "variants": "الأصناف",
      "newSale": "فاتورة جديدة",
      "customerName": "اسم الزبون",
      "selectProduct": "اختر المنتج",
      "unitPrice": "سعر الوحدة",
      "createSale": "إنشاء فاتورة",
      "recentSales": "آخر المبيعات",
      "invoiceNo": "رقم الفاتورة",
      "printInvoice": "طباعة الفاتورة",
      "businessName": "اسم المحل",
      "businessPhone": "رقم الهاتف",
      "businessAddress": "العنوان",
      "invoiceTitle": "عنوان الفاتورة",
      "footerNote": "ملاحظة أسفل الفاتورة",
      "terms": "الشروط",
      "logoUrl": "رابط الشعار",
      "color": "اللون",
      "showLogo": "إظهار الشعار",
      "showSignature": "إظهار التوقيع",
      "preview": "معاينة",
      "signature": "التوقيع",
      "billTo": "فاتورة إلى",
      "stockMovements": "حركات المخزون",
      "language": "اللغة",
      "theme": "المظهر",
      "english": "إنكليزي",
      "arabic": "عربي",
      "light": "فاتح",
      "dark": "داكن",
      "system": "حسب الجهاز",
      "exchangeRate": "سعر الصرف",
      "salesTotal": "إجمالي المبيع",
      "profit": "الربح",
      "comingSoon": "قريباً",
      "empty": "لا يوجد بيانات بعد.",
      "error": "خطأ",
      "refresh": "تحديث"
    }
  };

  static String get(String lang, String key) {
    return data[lang]?[key] ?? data["en"]?[key] ?? key;
  }
}

